### ISSUE TITLE
BaseEntity 사용 이유 찾아보기

### ISSUE THREAD

**Issue by oliveunji** [book-curation/book-curation-BE#3]

**Comment by oliveunji** [comment]
NestJS에서 entity repository는 특정 Database Entity와 상호작용하기 위한 인터페이스로써 사용되는 클래스였다.
Deprecated 된 이유는, TypeORM을 DB서비스에 주로 사용하는데, NestJS에서 TypeORM이 제공하는 같은 기능을 쓰는것을 권장하기 때문이다.

**Comment by oliveunji** [comment]
예제 코드
https://github.com/lujakob/nestjs-realworld-example-app/blob/master/src/user/user.entity.ts

EntityRepository extends 안하고, 그냥 Entity 데코레이터만 사용

**Comment by keongmini** [comment]
## TypeORM을 사용하는 패턴 두가지
Active Record Pattern VS Data Mapper Pattern

간단한 설명

* Active Record Pattern: entity에 직접 CRUD 하는 방식 (entity가 BaseEntity 상속 받아야함)
* Data Mapper Pattern: repository를 통해서 CRUD 하는 방식

전자는 간단한 프로젝트에서 단순하게 사용하기 좋고 후자는 유지보수가 용이하다는 장점이 있어서 큰 프로젝트에서 사용하기 좋다. 상황별로 선택해서 사용하면 된다고 공식문서에 써져있음

## 정리
우리는 Repository Pattern을 사용하기로 했기 때문에 자동으로 Data Mapper Pattern을 사용하게 됨!  
즉, BaseEntity를 상속할 필요 없음

> 참고  
> [Active Record vs Data Mapper](https://typeorm.io/active-record-data-mapper)
