### ISSUE TITLE
EntityRepository Deprecated 되었는데, 지금은 어떻게 사용할 수 있는지 찾아보기

### ISSUE THREAD

**Issue by oliveunji** [book-curation/book-curation-BE#4]

**Comment by oliveunji** [comment]
https://github.com/nestjs/nest/tree/master/sample/05-sql-typeorm/src

**Comment by keongmini** [comment]
## Repository Pattern
DB와 interact하는 CRUD(find, save, delete 등)은 repository / 비즈니스 로직은 service에서 하도록 분리

* EntityRepository를 사용하던 기존 방식은 custom repository를 사용하던 건데 deprecated 되면서 custom repository를 직접 만들어서 사용할 수 밖에 없는 상황

> 참고  
> [typeorm 0.3.x @EntityRepository 돌려줘~~](https://velog.io/@pk3669/typeorm-0.3.x-EntityRepository-%EB%8F%8C%EB%A0%A4%EC%A4%98)  
> [Custom repositories](https://typeorm.io/custom-repository)

* custom repository를 사용하지 않고 함수 안에서 injectRepository 데코레이터를 사용해서 repository(즉 entity manager) 역할을 하는 속성을 constructor에 정의 하는 방식이 있음 --> **우리 프로젝트에서는 이 방식을 사용하고자 함**

> 참고  
> https://github.com/nestjs/nest/tree/master/sample/05-sql-typeorm/src


## 결론
Repository Pattern을 사용하는 것은 맞다!  
하지만, EntityRepository를 사용해서 쉽게 custom repository를 사용할 수 있었던 TypeORM v2 대신 TypeORM v3을 사용할 것이기 때문에 InjectRepository를 사용하는 것 뿐이다
