### ISSUE TITLE
Book, Hashtag, Phrase Entity정의, BookItem Entity 삭제

### ISSUE THREAD

**Issue by keongmini** [book-curation/book-curation-BE#6]

**Comment by oliveunji** [comment]
- Book 정의: Book의 고유 정보 (Open소스 통해서 데이터 가져올 예정)

기존방식은 사용자가 직접 책을 업로드 할 수 있게 해서 BookItem을 따로 정의했지만, 
지금은 관리자가 책을 이미 올려놨다는 가정하에, 사용자가 책에대한 구절이나 해시테그만 추가/삭제 가능한 것으로 변경
그래서 BookItem에 대한 구현은 필요 없어지고 (클래스 필요없음, 삭제)
Phrase 랑 HashTag는 직접 Book을 참조 (외래키) 

댓글 기능은 없음. (추후 구현예정)
